#!/usr/bin/env bash
# Install daytrade as macOS launchd services so it NEVER silently dies.
#
# The failure this fixes (2026-06-02): daytrade ran as a manual foreground
# process with no supervisor. When its parent shell closed it received
# SIGTERM, shut down cleanly — and nothing restarted it. Capital-bearing
# bot, least-reliable setup. This script gives it the same belt-and-
# suspenders supervision nighttrade already has:
#
#   * com.daytrade.learn      — the 24/7 learning observer (under caffeinate
#                               so the Mac won't system-sleep and pause it)
#   * com.daytrade.dashboard  — the FastAPI dashboard on 0.0.0.0:<port>
#   * com.daytrade.watchdog   — fires every 5 min, kickstarts either service
#                               if it's down (defence-in-depth)
#
# launchd KeepAlive restarts on crash AND on reboot (RunAtLoad). The
# watchdog catches the gap where KeepAlive itself parks a job in throttle
# backoff.
#
# Usage:  deploy/install.sh [dashboard_port]      (port defaults to 8000)
#
# Paper / observation only — this never places a real trade.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="/usr/bin/python3"
AGENTS="$HOME/Library/LaunchAgents"
PORT="${1:-8000}"
WRAPPER="$REPO/deploy/_svc-run.sh"
U="$(id -u)"

echo "daytrade deploy"
echo "  repo : $REPO"
echo "  port : $PORT"

# Sanity check: the package and its deps must import under the chosen Python.
if ! PYTHONPATH="$REPO/src" "$PY" -c "import daytrade, fastapi, uvicorn, httpx" 2>/dev/null; then
  echo "ERROR: daytrade is not importable by $PY." >&2
  echo "Run first:  $PY -m pip install -e \".[dev]\"" >&2
  exit 1
fi

mkdir -p "$AGENTS" "$REPO/logs"

# A launchd-invoked wrapper that pins a known-good environment. launchd does
# not reliably pass HOME (needed to find user site-packages) or PYTHONPATH,
# so we bake them in here rather than depending on the plist environment.
# (Mirrors nighttrade/deploy/_svc-run.sh — the bare /usr/bin/python3 + relative
# PYTHONPATH=src in the old static plists was exactly why they were never
# safe to load.)
cat > "$WRAPPER" <<EOF
#!/bin/bash
# Generated by deploy/install.sh — pins the environment for launchd services.
export HOME="$HOME"
export PYTHONPATH="$REPO/src"
export PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
cd "$REPO" || exit 1
exec "\$@"
EOF
chmod +x "$WRAPPER"

# Stop anything already running outside launchd, and clear any stale
# single-instance lock left by a killed process so the new launchd-managed
# process can acquire it cleanly (avoids SingleInstanceLockError → throttle
# loop). Two-writer safety: we must have zero daytrade processes before
# launchd starts a fresh one.
pkill -f 'daytrade learn' 2>/dev/null || true
pkill -f 'daytrade observe' 2>/dev/null || true
pkill -f 'daytrade dashboard' 2>/dev/null || true
sleep 2
rm -f "$REPO/data/locks/learn.pid" 2>/dev/null || true

make_plist() {
  # Usage: make_plist <label> [--throttle SECONDS] <cmd...>
  local label="$1"; shift
  local throttle=10
  if [ "${1:-}" = "--throttle" ]; then
    throttle="$2"
    shift 2
  fi
  local plist="$AGENTS/$label.plist"
  {
    echo '<?xml version="1.0" encoding="UTF-8"?>'
    echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"' \
         '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
    echo '<plist version="1.0"><dict>'
    echo "  <key>Label</key><string>$label</string>"
    echo '  <key>ProgramArguments</key><array>'
    echo '    <string>/bin/bash</string>'
    echo "    <string>$WRAPPER</string>"
    for arg in "$@"; do echo "    <string>$arg</string>"; done
    echo '  </array>'
    echo "  <key>WorkingDirectory</key><string>$REPO</string>"
    echo '  <key>RunAtLoad</key><true/>'
    echo '  <key>KeepAlive</key><true/>'
    echo "  <key>ThrottleInterval</key><integer>$throttle</integer>"
    echo "  <key>StandardOutPath</key><string>$REPO/logs/$label.out.log</string>"
    echo "  <key>StandardErrorPath</key><string>$REPO/logs/$label.err.log</string>"
    echo '</dict></plist>'
  } > "$plist"
  launchctl bootout "gui/$U/$label" 2>/dev/null || true
  # Give launchd time to fully tear down the old job before bootstrapping.
  # A 1s settle raced on rapid re-deploys -> "Bootstrap failed: 5:
  # Input/output error" (observed 2026-06-03). Retry once before falling
  # back to the kickstart/watchdog safety net.
  sleep 2
  if ! launchctl bootstrap "gui/$U" "$plist" 2>/dev/null; then
    sleep 3
    launchctl bootstrap "gui/$U" "$plist" 2>/dev/null || \
      echo "  WARN: bootstrap $label failed twice — kickstart will recover it"
  fi
  echo "  loaded $label"
}

# The learning observer runs python DIRECTLY (no caffeinate wrapper in the
# job). caffeinate -s as the job's first process forks python as a child;
# when python dies launchd's job-completion detection + KeepAlive gets
# confused by the lingering caffeinate parent and fails to respawn
# (verified 2026-06-03: killing the tracked pid left the job dead). Running
# python directly means launchd tracks the real process and KeepAlive
# respawns cleanly. System-sleep is prevented by a SEPARATE, decoupled
# caffeinate service below, so the two concerns don't entangle.
# Canonical command per CLAUDE.md operational facts.
make_plist com.daytrade.learn \
  "$PY" -m daytrade learn --days 30 --interval 60 --real-data

# Dashboard binds 0.0.0.0 so tailnet peers can reach it on :$PORT.
make_plist com.daytrade.dashboard \
  "$PY" -m daytrade dashboard --host 0.0.0.0 --port "$PORT"

# Decoupled system-sleep preventer. `caffeinate -s` with no command runs
# until killed; KeepAlive restarts it if it ever dies. Keeping this in its
# OWN job (not wrapping the bot) is what lets the bot's KeepAlive work
# cleanly. The Mac stays awake 24/7 so the crypto bot keeps trading; the
# display can still sleep.
make_plist com.daytrade.caffeinate \
  /usr/bin/caffeinate -s

# Periodic watchdog — different semantics from learn/dashboard (it must
# NOT use KeepAlive). StartInterval=300 fires it every 5 min; the script
# exits quickly each run after its health check.
WATCHDOG_LABEL="com.daytrade.watchdog"
WATCHDOG_PLIST="$AGENTS/$WATCHDOG_LABEL.plist"
{
  echo '<?xml version="1.0" encoding="UTF-8"?>'
  echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"' \
       '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">'
  echo '<plist version="1.0"><dict>'
  echo "  <key>Label</key><string>$WATCHDOG_LABEL</string>"
  echo '  <key>ProgramArguments</key><array>'
  echo '    <string>/bin/bash</string>'
  echo "    <string>$REPO/deploy/watchdog.sh</string>"
  echo '  </array>'
  echo "  <key>WorkingDirectory</key><string>$REPO</string>"
  echo '  <key>RunAtLoad</key><true/>'
  echo '  <key>StartInterval</key><integer>300</integer>'
  echo "  <key>StandardOutPath</key><string>$REPO/logs/$WATCHDOG_LABEL.out.log</string>"
  echo "  <key>StandardErrorPath</key><string>$REPO/logs/$WATCHDOG_LABEL.err.log</string>"
  echo '</dict></plist>'
} > "$WATCHDOG_PLIST"
launchctl bootout "gui/$U/$WATCHDOG_LABEL" 2>/dev/null || true
sleep 1
launchctl bootstrap "gui/$U" "$WATCHDOG_PLIST"
echo "  loaded $WATCHDOG_LABEL  (fires every 300s, kicks learn + dashboard if down)"

# RunAtLoad does not reliably fire on bootstrap in the gui/ domain
# (observed 2026-06-03 — jobs loaded with runs=0 until kickstarted).
# Force-kick the long-running services so a fresh install actually
# starts them. The watchdog will RunAtLoad on its own StartInterval.
sleep 1
for svc in com.daytrade.caffeinate com.daytrade.learn com.daytrade.dashboard; do
  launchctl kickstart "gui/$U/$svc" >/dev/null 2>&1 || true
done
echo "  kickstarted learn + dashboard + caffeinate"

echo
echo "Done. The learning observer + dashboard now run as background services"
echo "that survive crashes, shell exits, and reboots."
echo "  dashboard : http://0.0.0.0:$PORT (tailnet-reachable)"
echo "  logs      : $REPO/logs/com.daytrade.*.log"
echo "  manage    : launchctl list | grep daytrade"
echo "  stop all  : deploy/uninstall.sh"
